//! ASS (Advanced SubStation Alpha) generation - the heart of the karaoke effect.
//!
//! ffmpeg renders ASS through libass, which supports per syllable karaoke tags
//! natively. That is why nothing here draws pixels: we describe the animation,
//! libass animates it, and one ffmpeg pass burns it into the video.
//!
//! Two shapes come out of here, see [`HighlightMode`]:
//!
//! * `KaraokeFill` writes one Dialogue event per caption line and one `\k` tag
//!   per word. libass draws a word in SecondaryColour until its karaoke slot
//!   starts and in PrimaryColour from then on, so the line fills up as it is
//!   spoken.
//! * `ActiveWord` writes one Dialogue event per word. Each event redraws the
//!   whole line but overrides the colour (and optionally the scale) of the one
//!   word being spoken, which is the look short form editors expect. The spoken
//!   duration is still emitted as a `\k` tag on that word.

use crate::style::{HighlightMode, SubtitleStyle};
use crate::word::Word;

/// Turn word timings into a complete, self contained ASS script.
///
/// The result is always a valid ASS file, even for an empty word list: header
/// and section markers are written unconditionally and only the Dialogue lines
/// depend on the input.
pub fn build_ass(words: &[Word], style: &SubtitleStyle) -> String {
    let mut out = String::with_capacity(2048 + words.len() * 48);
    write_header(&mut out, style);

    let groups = group_words(words, style);
    for (gi, group) in groups.iter().enumerate() {
        let hold_ms = hold_until(group, groups.get(gi + 1), style);
        match style.highlight {
            HighlightMode::KaraokeFill => write_karaoke_fill_line(&mut out, group, style, hold_ms),
            HighlightMode::ActiveWord => write_active_word_lines(&mut out, group, style, hold_ms),
        }
    }

    out
}

// --- header ---------------------------------------------------------------

fn write_header(out: &mut String, style: &SubtitleStyle) {
    let res_y = style.play_res_y.max(1) as f32;
    let res_x = style.play_res_x.max(1) as f32;

    let font_size = pct_of(res_y, style.font_size_pct).max(1.0).round() as u32;
    let outline = round2(pct_of(res_y, style.outline_pct));
    let shadow = round2(pct_of(res_y, style.shadow_pct));
    let margin_v = pct_of(res_y, style.margin_v_pct).round() as u32;
    let margin_h = pct_of(res_x, style.margin_h_pct).round() as u32;

    // In KaraokeFill the karaoke colour switch does the highlighting, so
    // Secondary is the unspoken colour and Primary the spoken one. In
    // ActiveWord the inline overrides do it, so both are the base colour and
    // the karaoke switch stays invisible.
    let (primary, secondary) = match style.highlight {
        HighlightMode::KaraokeFill => (style.highlight_color, style.base_color),
        HighlightMode::ActiveWord => (style.base_color, style.base_color),
    };

    out.push_str("[Script Info]\n");
    out.push_str("; Generated by Wortlaut - local, offline captioning\n");
    out.push_str("ScriptType: v4.00+\n");
    out.push_str("WrapStyle: 0\n");
    out.push_str("ScaledBorderAndShadow: yes\n");
    out.push_str("YCbCrMatrix: None\n");
    out.push_str(&format!("PlayResX: {}\n", style.play_res_x));
    out.push_str(&format!("PlayResY: {}\n", style.play_res_y));
    out.push('\n');

    out.push_str("[V4+ Styles]\n");
    out.push_str(
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, \
BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, \
Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n",
    );
    out.push_str(&format!(
        "Style: Default,{font},{size},{primary},{secondary},{outline_c},{back},{bold},0,0,0,\
100,100,0,0,1,{outline},{shadow},{align},{ml},{mr},{mv},1\n",
        font = style.font,
        size = font_size,
        primary = primary.to_ass_style(0),
        secondary = secondary.to_ass_style(0),
        outline_c = style.outline_color.to_ass_style(0),
        // Half transparent black box colour; only visible with BorderStyle 3.
        back = style.outline_color.to_ass_style(0x80),
        bold = if style.bold { -1 } else { 0 },
        outline = outline,
        shadow = shadow,
        align = style.alignment,
        ml = margin_h,
        mr = margin_h,
        mv = margin_v,
    ));
    out.push('\n');

    out.push_str("[Events]\n");
    out.push_str(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
}

// --- line building --------------------------------------------------------

/// How long a group may stay on screen: at least `min_line_ms`, but never past
/// the moment the next group starts, so lines can never overlap.
fn hold_until(group: &[Word], next: Option<&&[Word]>, style: &SubtitleStyle) -> u64 {
    let Some(first) = group.first() else { return 0 };
    let Some(last) = group.last() else { return 0 };
    let wanted = first.start_ms + style.min_line_ms;
    let limit = match next {
        Some(n) => n.first().map(|w| w.start_ms).unwrap_or(u64::MAX),
        None => u64::MAX,
    };
    last.end_ms.max(wanted.min(limit))
}

/// Split the word stream into caption lines.
///
/// A line ends when it is full, when the silence before the next word is longer
/// than `max_gap_ms`, or when it would stay on screen longer than `max_line_ms`.
fn group_words<'a>(words: &'a [Word], style: &SubtitleStyle) -> Vec<&'a [Word]> {
    let max_words = style.max_words_per_line.max(1);
    let mut groups: Vec<&[Word]> = Vec::new();
    let mut start = 0usize;

    for i in 0..words.len() {
        let is_last = i + 1 == words.len();
        let full = i - start + 1 >= max_words;
        let gap_break = !is_last && words[i + 1].start_ms.saturating_sub(words[i].end_ms) > style.max_gap_ms;
        let too_long = words[i].end_ms.saturating_sub(words[start].start_ms) >= style.max_line_ms;

        // A group that is on screen for less than min_line_ms flashes by
        // unread, so keep collecting unless the line is genuinely full, a real
        // pause follows, or it has hit the hard cap.
        let span_ms = words[i].end_ms.saturating_sub(words[start].start_ms);
        let too_short = span_ms < style.min_line_ms;

        if is_last || full || too_long || (gap_break && !too_short) {
            groups.push(&words[start..=i]);
            start = i + 1;
        }
    }

    groups
}

fn write_karaoke_fill_line(out: &mut String, group: &[Word], style: &SubtitleStyle, hold_ms: u64) {
    let Some(first) = group.first() else { return };
    let Some(last) = group.last() else { return };

    let mut text = String::new();
    let mut cursor = first.start_ms;
    for (i, w) in group.iter().enumerate() {
        // Silence inside the line becomes a blank karaoke slot, otherwise the
        // following word would light up too early.
        let gap = w.start_ms.saturating_sub(cursor);
        if gap > 0 {
            text.push_str(&format!("{{\\k{}}}", ms_to_cs(gap)));
        }
        text.push_str(&format!("{{\\k{}}}", ms_to_cs(w.duration_ms())));
        text.push_str(&render_word(&w.text, style));
        if i + 1 < group.len() {
            text.push(' ');
        }
        cursor = w.end_ms;
    }

    write_dialogue(out, first.start_ms, hold_ms.max(last.end_ms), &text);
}

fn write_active_word_lines(out: &mut String, group: &[Word], style: &SubtitleStyle, hold_ms: u64) {
    let base = style.base_color.to_ass_inline();
    let hi = style.highlight_color.to_ass_inline();
    let pop = style.highlight_scale.max(1);

    for (i, active) in group.iter().enumerate() {
        // Hold the line until the next word takes over so it does not blink
        // during the pause between two words.
        let end_ms = match group.get(i + 1) {
            Some(next) => next.start_ms.max(active.end_ms),
            // The last word of a line carries the hold, so a short line stays
            // readable instead of blinking away with the final syllable.
            None => hold_ms.max(active.end_ms),
        };

        let mut text = String::new();
        for (j, w) in group.iter().enumerate() {
            if j == i {
                text.push_str(&format!(
                    "{{\\k{k}\\1c{hi}\\fscx{pop}\\fscy{pop}}}",
                    k = ms_to_cs(w.duration_ms()),
                ));
            } else {
                text.push_str(&format!("{{\\1c{base}\\fscx100\\fscy100}}"));
            }
            text.push_str(&render_word(&w.text, style));
            if j + 1 < group.len() {
                text.push(' ');
            }
        }

        write_dialogue(out, active.start_ms, end_ms, &text);
    }
}

fn write_dialogue(out: &mut String, start_ms: u64, end_ms: u64, text: &str) {
    out.push_str(&format!(
        "Dialogue: 0,{},{},Default,,0,0,0,,{}\n",
        ass_time(start_ms),
        ass_time(end_ms.max(start_ms)),
        text
    ));
}

// --- helpers --------------------------------------------------------------

fn render_word(raw: &str, style: &SubtitleStyle) -> String {
    let text = if style.uppercase {
        raw.to_uppercase()
    } else {
        raw.to_string()
    };
    escape_ass_text(&text)
}

/// Make a transcribed word safe to drop into an ASS Text field.
///
/// Braces open and close override blocks and a backslash starts a tag, so a word
/// containing them would silently corrupt the line. Neither survives as itself
/// in ASS, so both are replaced rather than escaped.
fn escape_ass_text(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '{' => out.push('('),
            '}' => out.push(')'),
            '\\' => out.push('/'),
            '\n' | '\r' => out.push(' '),
            _ => out.push(ch),
        }
    }
    out
}

/// Milliseconds to centiseconds, the unit `\k` counts in. Rounds to nearest so
/// a run of words does not drift against the audio.
fn ms_to_cs(ms: u64) -> u64 {
    (ms + 5) / 10
}

/// ASS timestamps are `H:MM:SS.CC` with exactly two centisecond digits.
fn ass_time(ms: u64) -> String {
    let cs_total = ms / 10;
    let cs = cs_total % 100;
    let secs_total = cs_total / 100;
    let s = secs_total % 60;
    let m = (secs_total / 60) % 60;
    let h = secs_total / 3600;
    format!("{h}:{m:02}:{s:02}.{cs:02}")
}

fn pct_of(base: f32, pct: f32) -> f32 {
    base * pct / 100.0
}

fn round2(v: f32) -> f32 {
    (v * 100.0).round() / 100.0
}

// --- tests ----------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::style::{HighlightMode, StylePreset};

    fn words(spec: &[(&str, u64, u64)]) -> Vec<Word> {
        spec.iter()
            .map(|(t, a, b)| Word::new(*t, *a, *b))
            .collect()
    }

    fn fill_style() -> SubtitleStyle {
        StylePreset::KaraokeLine.style()
    }

    /// Pull every `\k<number>` out of the script, in order.
    fn k_values(ass: &str) -> Vec<u64> {
        let mut out = Vec::new();
        let mut rest = ass;
        while let Some(pos) = rest.find("\\k") {
            rest = &rest[pos + 2..];
            let digits: String = rest.chars().take_while(|c| c.is_ascii_digit()).collect();
            if !digits.is_empty() {
                out.push(digits.parse().unwrap());
            }
        }
        out
    }

    fn dialogue_lines(ass: &str) -> Vec<&str> {
        ass.lines().filter(|l| l.starts_with("Dialogue:")).collect()
    }

    #[test]
    fn header_has_the_sections_libass_needs() {
        let ass = build_ass(&words(&[("hallo", 0, 400)]), &fill_style());

        assert!(ass.starts_with("[Script Info]\n"), "script info must come first");
        for needle in [
            "ScriptType: v4.00+",
            "PlayResX: 1080",
            "PlayResY: 1920",
            "[V4+ Styles]",
            "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour,",
            "Style: Default,Avenir Next Demi Bold,",
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        ] {
            assert!(ass.contains(needle), "missing header piece: {needle}");
        }
        // Section order matters to libass parsers.
        assert!(ass.find("[V4+ Styles]") < ass.find("[Events]"));
    }

    #[test]
    fn k_values_are_word_durations_in_centiseconds() {
        let mut style = fill_style();
        style.max_words_per_line = 10;
        // Contiguous words, so no blank karaoke slots are inserted.
        let ws = words(&[("eins", 0, 300), ("zwei", 300, 750), ("drei", 750, 1000)]);

        let ass = build_ass(&ws, &style);

        assert_eq!(k_values(&ass), vec![30, 45, 25]);
    }

    #[test]
    fn silence_inside_a_line_becomes_a_blank_karaoke_slot() {
        let mut style = fill_style();
        style.max_words_per_line = 10;
        style.max_gap_ms = 5_000;
        // 200 ms of silence between the two words.
        let ws = words(&[("eins", 0, 300), ("zwei", 500, 900)]);

        let ass = build_ass(&ws, &style);

        // 30 for the first word, 20 for the pause, 40 for the second word.
        assert_eq!(k_values(&ass), vec![30, 20, 40]);
    }

    #[test]
    fn a_new_line_starts_after_n_words() {
        let mut style = fill_style();
        style.max_words_per_line = 3;
        style.max_line_ms = 60_000;
        let ws: Vec<Word> = (0..7)
            .map(|i| Word::new(format!("w{i}"), i * 200, i * 200 + 200))
            .collect();

        let ass = build_ass(&ws, &style);
        let lines = dialogue_lines(&ass);

        assert_eq!(lines.len(), 3, "7 words at 3 per line are 3 caption lines");
        assert_eq!(lines[0].matches("\\k").count(), 3);
        assert_eq!(lines[1].matches("\\k").count(), 3);
        assert_eq!(lines[2].matches("\\k").count(), 1, "last line holds the remainder");
    }

    #[test]
    fn empty_input_still_produces_a_valid_file() {
        let ass = build_ass(&[], &fill_style());

        assert!(ass.contains("[Script Info]"));
        assert!(ass.contains("[V4+ Styles]"));
        assert!(ass.contains("[Events]"));
        assert!(ass.trim_end().ends_with("Effect, Text"), "events section is declared but empty");
        assert_eq!(dialogue_lines(&ass).len(), 0, "no words means no Dialogue lines");
    }

    #[test]
    fn active_word_mode_redraws_the_line_once_per_word() {
        let mut style = StylePreset::BoldCenter.style();
        style.max_words_per_line = 3;
        style.max_line_ms = 60_000;
        assert_eq!(style.highlight, HighlightMode::ActiveWord);
        let ws = words(&[("eins", 0, 300), ("zwei", 300, 700), ("drei", 700, 1000)]);

        let ass = build_ass(&ws, &style);
        let lines = dialogue_lines(&ass);

        assert_eq!(lines.len(), 3, "one event per word");
        // Every event carries the full line, uppercased by this preset.
        for line in &lines {
            for w in ["EINS", "ZWEI", "DREI"] {
                assert!(line.contains(w), "line must repeat the whole caption: {line}");
            }
            assert_eq!(line.matches("\\k").count(), 1, "only the active word is timed");
        }
        // The active word carries the highlight colour and the scale pop.
        let hi = style.highlight_color.to_ass_inline();
        assert!(lines[1].contains(&format!("\\k40\\1c{hi}\\fscx112\\fscy112")));
    }

    #[test]
    fn timestamps_use_the_ass_hmmss_cc_format() {
        assert_eq!(ass_time(0), "0:00:00.00");
        assert_eq!(ass_time(1_500), "0:00:01.50");
        assert_eq!(ass_time(61_234), "0:01:01.23");
        assert_eq!(ass_time(3_723_450), "1:02:03.45");
    }

    #[test]
    fn braces_and_backslashes_in_a_word_cannot_break_the_line() {
        let mut style = fill_style();
        style.max_words_per_line = 10;
        let ws = words(&[("{evil}", 0, 200), ("a\\b", 200, 400)]);

        let ass = build_ass(&ws, &style);
        let line = dialogue_lines(&ass)[0];

        assert!(line.contains("(evil)"));
        assert!(line.contains("a/b"));
        // Exactly the two override blocks we wrote ourselves, no smuggled ones.
        assert_eq!(line.matches('{').count(), 2);
        assert_eq!(line.matches('}').count(), 2);
    }
}

#[cfg(test)]
mod readability_tests {
    use super::*;
    use crate::style::{StylePreset, SubtitleStyle};

    fn words(spans: &[(&str, u64, u64)]) -> Vec<Word> {
        spans
            .iter()
            .map(|(t, s, e)| Word { text: (*t).to_string(), start_ms: *s, end_ms: *e })
            .collect()
    }

    /// Parse "0:00:01.23" back into milliseconds so tests can assert on timing.
    fn parse_ts(ts: &str) -> u64 {
        let parts: Vec<&str> = ts.split(':').collect();
        let h: u64 = parts[0].parse().unwrap();
        let m: u64 = parts[1].parse().unwrap();
        let sec: f64 = parts[2].parse().unwrap();
        h * 3_600_000 + m * 60_000 + (sec * 1000.0).round() as u64
    }

    fn dialogue_spans(ass: &str) -> Vec<(u64, u64)> {
        ass.lines()
            .filter(|l| l.starts_with("Dialogue:"))
            .map(|l| {
                let f: Vec<&str> = l.split(',').collect();
                (parse_ts(f[1]), parse_ts(f[2]))
            })
            .collect()
    }

    #[test]
    fn a_short_final_line_is_held_long_enough_to_read() {
        let mut style = StylePreset::BoldCenter.style();
        style.min_line_ms = 1000;
        // Two quick words and then silence: without the hold this line would be
        // gone after 300ms.
        let ws = words(&[("kurz", 0, 150), ("weg", 150, 300)]);
        let spans = dialogue_spans(&build_ass(&ws, &style));
        let last = spans.last().copied().unwrap();
        assert!(
            last.1 - spans[0].0 >= 1000,
            "line should stay at least min_line_ms, got {:?}",
            last
        );
    }

    #[test]
    fn a_hold_never_runs_into_the_next_line() {
        let mut style = StylePreset::BoldCenter.style();
        style.min_line_ms = 2000;
        style.max_words_per_line = 1;
        style.max_gap_ms = 10;
        let ws = words(&[("eins", 0, 100), ("zwei", 400, 600)]);
        let spans = dialogue_spans(&build_ass(&ws, &style));
        assert!(spans.len() >= 2, "expected separate lines, got {spans:?}");
        for pair in spans.windows(2) {
            assert!(
                pair[0].1 <= pair[1].0,
                "line {:?} overlaps the next {:?}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn fast_speech_merges_into_readable_groups() {
        let mut style = StylePreset::BoldCenter.style();
        style.min_line_ms = 1000;
        style.max_words_per_line = 4;
        style.max_gap_ms = 60;
        // Six rapid words with small gaps: grouping must not produce one line
        // per word just because each gap slightly exceeds max_gap_ms.
        let ws = words(&[
            ("a", 0, 120),
            ("b", 200, 320),
            ("c", 400, 520),
            ("d", 600, 720),
            ("e", 800, 920),
            ("f", 1000, 1400),
        ]);
        let groups = group_words(&ws, &style);
        assert!(
            groups.len() <= 2,
            "fast speech should merge, got {} groups",
            groups.len()
        );
    }

    #[test]
    fn a_real_pause_after_a_long_enough_line_still_breaks() {
        let mut style = StylePreset::BoldCenter.style();
        style.min_line_ms = 800;
        style.max_words_per_line = 8;
        style.max_gap_ms = 500;
        let ws = words(&[("lang", 0, 900), ("danach", 2000, 2400)]);
        let groups = group_words(&ws, &style);
        assert_eq!(groups.len(), 2, "a real pause must start a new line");
    }
}
